json_file_list = [
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.1',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.2',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.3',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.4',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.5',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.6',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.7',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.8',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.9',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.10',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.11',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.12',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.13',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.14',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.15',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.16',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.17',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.18',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.19',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.20',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.21',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.22',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.23',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.24',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.25',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.26',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.27',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.28',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.29',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.30',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.31',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.32',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.33',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.34',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.35',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.36',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.37',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.38',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.39',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.40',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.41',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.42',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.43',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.44',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.45',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.46',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.47',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.48',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.49',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.50',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.51',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.52',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.53',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.54',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.55',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.56',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.57',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.58',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.59',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.60',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.61',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.62',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.63',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.64',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.65',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.66',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.67',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.68',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.69',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.70',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.71',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.72',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.73',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.74',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.75',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.76',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.77',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.78',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.79',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.80',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.81',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.82',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.83',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.84',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.85',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.86',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.87',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.88',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.89',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.90',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.91',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.92',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.93',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.94',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.95',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.96',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.97',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.98',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.99',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.100',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.101',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.102',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.103',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.104',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.105',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.106',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.107',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.108',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.109',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.110',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.111',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.112',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.113',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.114',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.115',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.116',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.117',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.118',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.119',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.120',
        '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.121',
        '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.122',
        '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.123',
        '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.124',
        '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.125',
        '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.126',
        '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.127',
        '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.128',
        '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.129',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.130',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.131',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.132',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.133',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.134',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.135',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.136',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.137',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.138',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.139',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.140',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.141',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.142',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.143',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.144',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.145',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.146',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.147',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.148',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.149',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.150',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.151',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.152',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.153',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.154',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.155',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.156',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.157',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.158',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.159',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.160',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.161',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.162',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.163',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.164',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.165',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.166',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.167',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.168',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.169',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.170',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.171',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.172',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.173',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.174',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.175',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.176',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.177',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.178',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.179',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.180',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.181',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.182',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.183',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.184',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.185',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.186',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.187',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.188',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.189',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.190',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.191',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.192',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.193',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.194',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.195',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.196',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.197',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.198',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.199',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.200',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.201',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.202',
        # '/home/yangyangwei/dataset/trace/ta1-trace-e3-official.json.203',
        '/home/yangyangwei/dataset/trace/ta1-trace-e3-official-1.json',
        '/home/yangyangwei/dataset/trace/ta1-trace-e3-official-1.json.1',
        '/home/yangyangwei/dataset/trace/ta1-trace-e3-official-1.json.2',
        '/home/yangyangwei/dataset/trace/ta1-trace-e3-official-1.json.3',
        '/home/yangyangwei/dataset/trace/ta1-trace-e3-official-1.json.4',
        '/home/yangyangwei/dataset/trace/ta1-trace-e3-official-1.json.5',
        '/home/yangyangwei/dataset/trace/ta1-trace-e3-official-1.json.6'
]

event_csv_list = [
        '/home/yangyangwei/dataset/trace_e3_preparation/e3_trace_preparation_event_12.csv'
]

event_npy_list = [
        '/home/yangyangwei/dataset/trace_e3_preparation/e3_trace_preparation_event_12.npy'
]

event_csv_predict_list = [
        '/home/yangyangwei/dataset/trace_e3_preparation/e3_trace_preparation_event_12_predict.csv'
]

log_list = [
        '/home/yangyangwei/dataset/trace_e3_preparation/e3_trace_preparation_12.json',
]

class LOG_TYPE:
        FILE_OP = ['EVENT_OPEN', 'EVENT_READ', 'EVENT_WRITE', 'EVENT_MODIFY_FILE_ATTRIBUTES', 'EVENT_LOADLIBRARY']
        PROCESS_OP = ['EVENT_FORK', 'EVENT_MODIFY_PROCESS', 'EVENT_EXECUTE']
        NET_OP = ['EVENT_RECVMSG', 'EVENT_SENDMSG', 'EVENT_CONNECT']

class EVENT_TYPE:
        EVENT_OP = ['EVENT_OPEN', 'EVENT_READ', 'EVENT_WRITE', 'EVENT_EXECUTE', 'EVENT_MODIFY_FILE_ATTRIBUTES', 'EVENT_FORK', 'EVENT_MODIFY_PROCESS', 'EVENT_RECVMSG', 'EVENT_SENDMSG', 'EVENT_CONNECT', 'EVENT_LOADLIBRARY']

event_dict = {
        'EVENT_OPEN': 'file read',
        'EVENT_READ': 'file read',
        'EVENT_WRITE': 'file write',
        'EVENT_MODIFY_FILE_ATTRIBUTES': 'file modify',
        'EVENT_LOADLIBRARY': 'file read',
        'EVENT_EXECUTE': 'process execute',
        'EVENT_FORK': 'process fork',
        'EVENT_CONNECT': 'network send',
        'EVENT_RECVMSG': 'network receive',
        'EVENT_SENDMSG': 'network send',
        'EVENT_MODIFY_PROCESS': 'process modify'
}